/**
 * yaml2js.js
 * 从 data/knowledge-base.yaml 读取知识库，输出 src/data.js
 *
 * 依赖: npm install js-yaml
 * 用法: node scripts/yaml2js.js
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const YAML_PATH = path.join(__dirname, "..", "data", "knowledge-base.yaml");
const JS_OUT = path.join(__dirname, "..", "src", "data.js");

const yamlSrc = fs.readFileSync(YAML_PATH, "utf-8");
const parsed = yaml.load(yamlSrc);
const nodes = parsed.nodes || [];

const js = `// THIS FILE IS AUTO-GENERATED BY scripts/yaml2js.js -- DO NOT EDIT
// Source: data/knowledge-base.yaml
// Generated: ${new Date().toISOString()}

const KNOWLEDGE_BASE = ${JSON.stringify(nodes, null, 2)};
`;

const srcDir = path.dirname(JS_OUT);
if (!fs.existsSync(srcDir)) fs.mkdirSync(srcDir, { recursive: true });
fs.writeFileSync(JS_OUT, js, "utf-8");
console.log("✓ Generated " + JS_OUT + " (" + nodes.length + " nodes)");