// THIS FILE IS AUTO-GENERATED BY scripts/yaml2js.js -- DO NOT EDIT
// Source: data/knowledge-base.yaml
// Generated: 2026-04-19T11:18:25.640Z

const KNOWLEDGE_BASE = [
  {
    "id": "k000",
    "title": "图形渲染管线概述",
    "description": "理解 GPU 渲染管线的各阶段，从顶点输入到片段输出的完整流程",
    "type": "concept",
    "difficulty": 2,
    "importance": 5,
    "tags": [
      "pipeline",
      "basics"
    ],
    "prerequisites": [],
    "resources": [
      {
        "type": "doc",
        "title": "LearnOpenGL - 你好三角形",
        "url": "https://learnopengl.com/Getting-started/Hello-Triangle"
      },
      {
        "type": "source",
        "title": "最小三角形示例",
        "path": "./courses/01-intro/triangle.cpp"
      }
    ],
    "estimated_minutes": 30,
    "related_nodes": [
      "k001"
    ]
  },
  {
    "id": "k001",
    "title": "着色器基础 (Shader Basics)",
    "description": "GLSL 语法、顶点着色器与片段着色器的编写与交互",
    "type": "concept",
    "difficulty": 2,
    "importance": 4,
    "tags": [
      "shader",
      "glsl",
      "vulkan-note"
    ],
    "prerequisites": [
      "k000"
    ],
    "resources": [
      {
        "type": "doc",
        "title": "LearnOpenGL - 着色器章节",
        "url": "https://learnopengl.com/Getting-started/Shaders"
      },
      {
        "type": "source",
        "title": "着色器源码",
        "path": "./courses/01-intro/shaders/basic.cpp"
      }
    ],
    "estimated_minutes": 45,
    "related_nodes": [
      "k002",
      "k003"
    ]
  },
  {
    "id": "k002",
    "title": "顶点缓冲区 (VBO/VAO)",
    "description": "顶点数据的上传、VAO/VBO 的创建与绑定、顶点属性的配置",
    "type": "concept",
    "difficulty": 3,
    "importance": 4,
    "tags": [
      "buffers",
      "vao",
      "vbo"
    ],
    "prerequisites": [
      "k001"
    ],
    "resources": [
      {
        "type": "doc",
        "title": "LearnOpenGL - 顶点属性配置",
        "url": "https://learnopengl.com/Getting-started/Vertex-Attributes"
      },
      {
        "type": "pitfall",
        "title": "VAO/VBO 绑定顺序陷阱",
        "common_error": "忘记绑定 VAO 就绑定 VBO",
        "cause": "VBO 创建在 VAO 绑定之前，导致属性指针配置不生效",
        "solution": "始终遵循: 创建VBO → 绑定VAO → 配置属性 → 解绑"
      },
      {
        "type": "source",
        "title": "VBO/VAO 示例",
        "path": "./courses/02-buffers/vao_vbo.cpp"
      }
    ],
    "estimated_minutes": 40,
    "related_nodes": [
      "k003",
      "k004"
    ]
  },
  {
    "id": "k003",
    "title": "纹理映射 (Texture Mapping)",
    "description": "纹理创建、绑定、过滤方式、环绕模式、多级渐远纹理",
    "type": "concept",
    "difficulty": 3,
    "importance": 4,
    "tags": [
      "texture",
      "sampling"
    ],
    "prerequisites": [
      "k002"
    ],
    "resources": [
      {
        "type": "doc",
        "title": "LearnOpenGL - 纹理",
        "url": "https://learnopengl.com/Getting-started/Textures"
      },
      {
        "type": "source",
        "title": "纹理加载示例",
        "path": "./courses/03-texture/texture.cpp"
      }
    ],
    "estimated_minutes": 50,
    "related_nodes": [
      "k004"
    ]
  },
  {
    "id": "k004",
    "title": "帧缓冲 (Framebuffer Object)",
    "description": "FBO 的创建、渲染到纹理、屏幕后处理效果的实现",
    "type": "concept",
    "difficulty": 4,
    "importance": 3,
    "tags": [
      "fbo",
      "post-processing",
      "rtt"
    ],
    "prerequisites": [
      "k003"
    ],
    "resources": [
      {
        "type": "doc",
        "title": "LearnOpenGL - 帧缓冲",
        "url": "https://learnopengl.com/Advanced-OpenGL/Framebuffers"
      },
      {
        "type": "pitfall",
        "title": "FBO 完整性检查",
        "common_error": "渲染到 FBO 后忘记重新绑定到默认帧缓冲",
        "cause": "之后所有绘制都在 FBO 的纹理上，看不到任何输出",
        "solution": "完成后调用 glBindFramebuffer(GL_FRAMEBUFFER, 0)"
      },
      {
        "type": "source",
        "title": "FBO 后处理示例",
        "path": "./courses/04-fbo/post_process.cpp"
      }
    ],
    "estimated_minutes": 60,
    "related_nodes": []
  }
];
